### ISSUE TITLE
Release - indev1

### ISSUE THREAD

**Issue by Haltroy** [Haltroy/Yorot.Avalonia#15]
# Important

First version lol

# ToDo:

## First Batch:
 - #11 
 - #5 
 - #13 
 - #2 
 - #6
 - #8
 - #9 
 - #10
 - #14 
 - #17
 - #18 

## Second Batch:
 - #7 
 - #20 
 - #19 
 - #4
 - #1 
 - #3 
 - #22 
 - #24 
 - #25 
 - #21
 - #23 
 - [ ] [Yorot.Standart 1.0 final](https://github.com/Haltroy/Yorot.Standart/issues/1)
 - [ ] [Yorot Apps](https://github.com/Haltroy/YorotApps/issues/1)
 - [ ] [Yorot App Designer](https://github.com/Haltroy/YorotAppDesigner)

## Third Batch:
 - [ ] Try to implement leftover issues attached to this milestone or the Zero milestone.
 - [ ] Fix TODOs inside the code.
 - [ ] Cleanup and organize code.
 - [ ] Optimize code.

## Release Batch:
 - [ ] Release to GitHub Releases.
 - [ ] Release to website.

**Comment by Haltroy** [comment]
Development paused till next friday, i fucked up my finals.
