### ISSUE TITLE
Global Navigation Bar

### ISSUE THREAD

**Issue by Haltroy** [Haltroy/Yorot.Avalonia#17]
Instead of rendering a global navigation bar, Yorot spawns multiple navigation bars for each tab. This eats a lot of RAM.

Mentioned in #16.

## TODO:

- [x] Move the navigation bar to MainWindow.
- [x] Fix tab window
- [x] Check stuff from tab window
  - [x] URL bar
  - [x] Page Security
  - [x] Back/Forward
  - [x] Refresh/Stop
  - [x] Find
  - [x] Un/Mute

**Comment by Haltroy** [comment]
Everything except zoom feature is working.
