### ISSUE TITLE
OOBE ToDo

### ISSUE THREAD

**Issue by Haltroy** [Haltroy/Yorot.Avalonia#4]
- [x] Add Out-of-Box-Experience window
   - [x] Language & locale selection map (yes, a map, just like those linux distro installers)
   - [x] User Creation
   - [x] Theme Selection
   - [x] Add all locales to the list.
   - [x] Import from other browser
      - [x] Chromium-based (JSON)
          - [x] Chrome
          - [x] Edge
          - [x] Opera
          - [x] Opera GX
          - [x] Chromium-based
      - [x] HTML/XML
          - [x] other Yorot flavor (XML)
          - [x] HTML file

**Comment by Haltroy** [comment]
now i need to figure out importing stuff and that map-country-lang-locale-datetime thing

**Comment by Haltroy** [comment]
~~Opera might be different~~, also dropped Edge Legacy, Korot and IE because they are too old and not cross-platform.

EDIT: I will resurrect Korot this or next weekend. Korot will self-destruct (again) when Yorot is out but this time it will check if Yorot is out or not from GitHub, it will also contain a tool that converts Korot data into Yorot data.

**Comment by Haltroy** [comment]
Sorry for closing too early. Also dropped Firefox.
Firefox users can still import to Yorot from a HTML file. SQLite is too complex for my non-existent brain.

**Comment by Haltroy** [comment]
Finally, It's done. I'll push the changes later.
Also, made the entire bookmark thing as a library so anyone who's going to make a program using it to manage bookmarks across platforms and browsers to easily read it. I haven't implemented a save function so no virus that uses the library can add the stupid spam stuff into people's bookmarks.
